# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

flutter_application_path = '../funda_demo'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'funda_demo_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for funda_demo_ios
  install_all_flutter_pods(flutter_application_path)

end
